# docker-compose.prod.yml
version: '3.8'

services:
  api:
    build: ./backend
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
