# docker-compose.yml (Desenvolvimento com MySQL)

services:
  # Serviço do Banco de Dados MySQL
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=carteira_dev
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serviço da nossa API Django
  api:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      # Variáveis para a API se conectar ao serviço 'db'
      - MYSQL_DATABASE=carteira_dev
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - DB_HOST=db  # Importante: o host é o nome do serviço 'db'
      - MYSQL_PORT=3306
    depends_on:
      db:
        condition: service_healthy # Garante que a API só inicia depois do DB
    user: "1000:1000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - api

volumes:
  mysql_data: # Define o volume que será usado pelo serviço 'db'