# docker-compose.prod.yml

services:
  api:
    build: ./backend
    command: sh -c "python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    volumes:
      - staticfiles_volume:/app/staticfiles # A api ESCREVE os arquivos estáticos aqui
    env_file:
      - .env.production
    # SEM PORTAS EXPOSTAS, mais seguro

  frontend:
    build: ./frontend
    volumes:
      - staticfiles_volume:/vol/static:ro # O frontend LÊ os arquivos daqui (somente leitura)
    ports:
      - "3000:80" # A porta que o Load Balancer irá acessar
    depends_on:
      - api

volumes:
  staticfiles_volume: # O volume compartilhado
